export const subjects = {
  GET_STATUS: 'GET_STATUS',
  GET_ACCOUNT: 'GET_ACCOUNT',
  SIGN_MESSAGE: 'SIGN_MESSAGE'
}

export const status = {
  NOT_INSTALLED: 'NOT_INSTALLED',
  NOT_INITIALIZED: 'NOT_INITIALIZED',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  READY: 'READY'
}